name: Build Blog-only

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build Blog-only
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Set up Node
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3
        with:
          node-version: '16'
          cache: yarn
      - name: Installation
        run: yarn
      - name: Build blog-only
        run: yarn workspace website build:blogOnly
